spring:
  redis:
    host: 192.168.10.102 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码（默认为空）
    database: 0 # Redis数据库索引（默认为0）
    timeout: 3000ms # 连接超时时间（默认0毫秒，表示永不超时）
    client-type: lettuce # 配置客户端技术类型，设置为lettuce
    lettuce:
      pool:
        max-active: 8  # 连接池最大连接数，默认8（使用负值表示没有限制）
        max-wait: 100ms # 连接池最大阻塞等待时间，默认-1（使用负值表示没有限制）
        max-idle: 8     # 连接池最大空闲连接，默认8
        min-idle: 0     # 连接池中最小空闲连接，默认0
    jedis:
      pool:
        max-active: 8   # 连接池最大连接数，默认8（使用负值表示没有限制）
        max-wait: 100ms # 连接池最大阻塞等待时间，默认-1（使用负值表示没有限制）
        max-idle: 8     # 连接池最大空闲连接，默认8
        min-idle: 0     # 连接池中最小空闲连接，默认0
    # cluster 集群配置
    cluster:
      max-redirects: 3  # 获取失败 最大重定向次数
      nodes:
      - 192.168.10.102:6379
      - 192.168.10.102:6380
      - 192.168.10.102:6381
      - 192.168.10.102:6382
      - 192.168.10.102:6383
      - 192.168.10.102:6384